from __future__ import annotations

"""fixturedownload / broadcast club names -> ClubElo names (shared by the
European simulator, the validation scripts and the app)."""

CLUB_ALIASES: dict[str, str] = {
    "bayern munich": "Bayern", "atletico madrid": "Atletico", "atletico de madrid": "Atletico",
    "man city": "ManCity", "manchester city": "ManCity", "man utd": "ManUnited",
    "manchester united": "ManUnited", "paris saint-germain": "ParisSG", "psg": "ParisSG",
    "inter milan": "Inter", "ac milan": "Milan", "bayer leverkusen": "Leverkusen",
    "borussia dortmund": "Dortmund", "rb leipzig": "RBLeipzig", "sporting cp": "Sporting",
    "sporting lisbon": "Sporting", "fc porto": "Porto", "sl benfica": "Benfica",
    "psv eindhoven": "PSV", "az alkmaar": "AZAlkmaar", "crvena zvezda": "CrvenaZvezda",
    "red star belgrade": "CrvenaZvezda", "fc copenhagen": "FCKobenhavn",
    "copenhagen": "FCKobenhavn", "club brugge": "Brugge", "union berlin": "UnionBerlin",
    "eintracht frankfurt": "Frankfurt", "real sociedad": "Sociedad", "celtic fc": "Celtic",
    "rangers fc": "Rangers", "young boys": "YoungBoys", "red bull salzburg": "Salzburg",
    "rb salzburg": "Salzburg", "shakhtar donetsk": "Shakhtar", "dinamo zagreb": "DinamoZagreb",
    "slavia prague": "SlaviaPraha", "sparta prague": "SpartaPraha", "viktoria plzen": "Plzen",
    "bodo/glimt": "Bodoe/Glimt", "bodo / glimt": "Bodoe/Glimt", "malmo ff": "Malmoe",
    "besiktas": "Besiktas", "fenerbahce": "Fenerbahce", "galatasaray": "Galatasaray",
    "olympiacos": "Olympiakos", "olympiacos piraeus": "Olympiakos", "paok": "PAOK",
    "aek athens": "AEK", "sturm graz": "SturmGraz", "slovan bratislava": "SlovanBratislava",
    "st gilloise": "UnionStGilloise", "union saint-gilloise": "UnionStGilloise",
    "royale union sg": "UnionStGilloise", "girona fc": "Girona", "stade brestois": "Brest",
    "vfb stuttgart": "Stuttgart", "sc freiburg": "Freiburg", "olympique marseille": "Marseille",
    "olympique lyonnais": "Lyon", "lyon": "Lyon", "nice": "Nice", "lens": "Lens", "lille": "Lille",
    "spurs": "Tottenham", "tottenham hotspur": "Tottenham", "west ham united": "WestHam",
    "wolverhampton": "Wolves", "leicester city": "Leicester", "sevilla fc": "Sevilla",
    "villarreal cf": "Villarreal", "real betis": "Betis", "athletic club": "Bilbao",
    "athletic bilbao": "Bilbao", "feyenoord rotterdam": "Feyenoord", "ajax amsterdam": "Ajax",
    "twente": "Twente", "sc braga": "Braga", "vitoria de guimaraes": "Guimaraes",
    "ludogorets razgrad": "Ludogorets", "qarabag fk": "Qarabag", "ferencvaros": "Ferencvaros",
    "maccabi haifa": "MaccabiHaifa", "maccabi tel aviv": "MaccabiTelAviv",
    "molde fk": "Molde", "rosenborg": "Rosenborg", "legia warsaw": "LegiaWarszawa",
    "lech poznan": "LechPoznan", "rakow": "Rakow", "servette fc": "Servette",
    "fc basel": "Basel", "fc zurich": "Zuerich", "fc lugano": "Lugano",
    "atleti": "Atletico", "atlético": "Atletico", "atlético de madrid": "Atletico",
    "bayern": "Bayern", "bayern münchen": "Bayern", "fenerbahçe": "Fenerbahce",
    "ferencváros": "Ferencvaros", "djurgården": "Djurgarden", "häcken": "Haecken",
    "bröndby": "Broendby", "brøndby": "Broendby", "malmö": "Malmoe",
    "köln": "Koeln", "gnk dinamo": "DinamoZagreb", "fcsb": "FCSB",
    "basaksehir": "Basaksehir", "başakşehir": "Basaksehir",
    "paris": "ParisSG", "s. bratislava": "SlovanBratislava", "shakhtar": "ShakhtarDonetsk",
    "stuttgart": "Stuttgart", "losc": "Lille", "leicester": "Leicester",
    "m. haifa": "MaccabiHaifa", "raków": "Rakow", "sk rapid": "RapidWien",
    "omonoia": "Omonia", "qarabag": "Qarabag", "ludogorets": "Ludogorets",
}


# ClubElo name -> foundation (football-data lowercase) name, for the big-5 clubs
# that our domestic engine / props / player models know. Used to upgrade European
# match analysis to the full domestic models when both sides are covered.
CLUBELO_TO_FD: dict[str, str] = {
    "Arsenal": "arsenal", "ManCity": "man city", "Man City": "man city",
    "ManUnited": "man united", "Man United": "man united", "Liverpool": "liverpool",
    "Chelsea": "chelsea", "Tottenham": "tottenham", "Newcastle": "newcastle",
    "AstonVilla": "aston villa", "Aston Villa": "aston villa", "WestHam": "west ham",
    "West Ham": "west ham", "Brighton": "brighton", "Bournemouth": "bournemouth",
    "Everton": "everton", "Forest": "nott'm forest", "CrystalPalace": "crystal palace",
    "Crystal Palace": "crystal palace", "Fulham": "fulham", "Brentford": "brentford",
    "Wolves": "wolves", "Real Madrid": "real madrid", "RealMadrid": "real madrid",
    "Barcelona": "barcelona", "Atletico": "ath madrid", "Sevilla": "sevilla",
    "Villarreal": "villarreal", "Sociedad": "sociedad", "Betis": "betis",
    "Bilbao": "ath bilbao", "Girona": "girona", "Valencia": "valencia",
    "Osasuna": "osasuna", "Celta": "celta", "Getafe": "getafe", "Mallorca": "mallorca",
    "Bayern": "bayern munich", "Dortmund": "dortmund", "Leverkusen": "leverkusen",
    "RBLeipzig": "rb leipzig", "RB Leipzig": "rb leipzig", "Frankfurt": "ein frankfurt",
    "Stuttgart": "stuttgart", "UnionBerlin": "union berlin", "Union Berlin": "union berlin",
    "Freiburg": "freiburg", "Hoffenheim": "hoffenheim", "Gladbach": "m'gladbach",
    "Werder": "werder bremen", "Wolfsburg": "wolfsburg", "Mainz": "mainz",
    "Inter": "inter", "Milan": "milan", "Juventus": "juventus", "Napoli": "napoli",
    "Roma": "roma", "Lazio": "lazio", "Atalanta": "atalanta", "Fiorentina": "fiorentina",
    "Bologna": "bologna", "Torino": "torino", "ParisSG": "paris sg", "Paris SG": "paris sg",
    "Marseille": "marseille", "Monaco": "monaco", "Lille": "lille", "Lyon": "lyon",
    "Nice": "nice", "Lens": "lens", "Brest": "brest", "Rennes": "rennes",
    "Strasbourg": "strasbourg", "Toulouse": "toulouse", "Nantes": "nantes",
}
